### ISSUE TITLE
Elements/forms can't be clicked when they are hidden/obscured

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-web#48]
## Problem / Motivation
Many of the steps we have available in the Web Cog allow interaction with elements that are not necessarily intractable by real users (e.g. because they are hidden or obscured).  This is **by design**: our aim is to strike a friendlier balance between _behaves exactly as a real browser/user would_ vs. _sensible, easy test setup and outcomes_.

The problem is that we are not consistent in this: interaction steps that include clicks will sometimes work (as in the case of filling out a form with a checkbox field), but other times won't (e.g. on the `click the page element` and `submit the form by clicking` steps)

## Proposed Resolution
The underlying issue appears to be that [Puppeteer's native click handler](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#frameclickselector-options) closely simulates a real user click...

> This method fetches an element with selector, scrolls it into view if needed, and then uses page.mouse to click in the center of the element. If there's no element matching selector, the method throws an error.

...But doesn't know/throw an error when the element was not actually successfully clicked (only when the element literally can't be found in the DOM)

### Approaches

**Approach 1**: Use `.evalute()` instead of `.click()`

```javascript
// Replace this...
await this.client['___currentFrame'].click(selector);

// With something like, ensuring we still throw/reject when element doesn't exist
await this.client['___currentFrame'].evaluate(
  async (selector) => {
    const $elem = document.querySelector(selector);
    return $elem ? $elem.click() : Promise.reject();
  },
  selector,
);
```

This has the benefit of being simple and efficient, but there is a slim possibility of strange behavior in edge-cases.  This is also how the `fill out form field` works on check boxes already.

**Approach 2**: Use a `.waitForFunction()` that adds a click handler to the given element and resolves when the click handler is invoked, in combination with the Puppeteer native `.click()` method.  ...And fall back to the approach above.

```javascript
try {
  await Promise.all([
    this.client['___currentFrame'].waitForFunction(
      (selector) => {
        return new Promise((resolve, reject) => {
          try {
            document.querySelector(selector).addEventListener('click', resolve);
          } catch (e) {
            reject(e);
          }
        });
      },
      {timeout: 2000},
      selector,
    ),
    this.client['___currentFrame'].click(selector);
      async (selector) => {
        const $elem = document.querySelector(selector);
        return $elem ? $elem.click() : Promise.reject();
      },
      selector,
    )
  ]);
} catch (e) {
  // Fallback to this.client['__currentFrame'].evaluate() with $elem.click() approach from above
}
```

---

Whatever the approach, the change will need to be made in the following methods:
- [ ] `BasicInteractionAware::submitFormByClickingButton()`
- [ ] `BasicInteractionAware::clickElement()`

This is a follow-up to issues encountered in #44.

**Comment by amcpanaligan** [comment]
Should we just remove the first `try-catch` block since it never throws?:

https://github.com/run-crank/cog-web/blob/master/src/client/mixins/basic-interaction.ts#L62

**Comment by iamEAP** [comment]
Yes!  This is a much simpler way of doing what I was proposing.
