### ISSUE TITLE
Implement Mixin Pattern on Existing Steps

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-web#5]
## Problem / Motivation
We are about to begin adding a lot of steps to this Cog, which will add a tremendous amount of code to the `ClientWrapper` unless we do something about it.

## Scope / UAT Target
- [ ] The `ClientWrapper` file should contain the functionality/code necessary to apply mixins to the `ClientWrapper` class before exporting it.
- [ ] The `navigateToUrl`, `fillOutField` `submitFormByClickingButton`, and `getFieldMethod` methods should be split into a `BasicInteractionAware` mixin.
- [ ] The `getMetaTagContent` method should be split into a `DomAware` mixin.
- [ ] The `getCurrentPageInfo` method should be split into a `ResponseAware` mixin.
- [ ] All existing unit tests and functionality should be otherwise unaffected.

**Comment by amcpanaligan** [comment]
It seems that I cannot assign myself, still.

**Comment by iamEAP** [comment]
@amcpanaligan try now?

**Comment by amcpanaligan** [comment]
> @amcpanaligan try now?

Dekimasu!

**Comment by amcpanaligan** [comment]
Is there a way to _actually_ tick-off those items in the checklist?
